title: Prof Xiaojun Chang@UTS
author: Prof Xiaojun Chang@UTS
url: "https://www.xiaojun.ai"
baseurl: ""

description: Prof Xiaojun Chang's academic website

markdown: kramdown

google_analytics_tracking_id: UA-109052064-1

sass:
    style: compressed
    sass_dir: _sass

include: ["_pages"]

google_scholar_url:   https://scholar.google.com/citations?hl=en&user=8suupocAAAAJ
github_username:      cxj273
linkedin_username:    oscar-xiaojun-chang-47a4525b
quora_username:       cxj273
wordpress_username:   cxj273
facebook_username:    cxj273
twitter_username:     cxj273
google_plus_username: cxj273
